/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdjustTimeOffBalance
 */
export interface AdjustTimeOffBalance {
    /**
     * The date the adjustment should be added in history. Should be in ISO8601 date format (YYYY-MM-DD).
     * @type {string}
     * @memberof AdjustTimeOffBalance
     */
    'date': string;
    /**
     * The ID of the time off type to add a balance adjustment for.
     * @type {number}
     * @memberof AdjustTimeOffBalance
     */
    'timeOffTypeId': number;
    /**
     * The number of hours/days to adjust the balance by.
     * @type {number}
     * @memberof AdjustTimeOffBalance
     */
    'amount': number;
    /**
     * This is an optional note to show in history.
     * @type {string}
     * @memberof AdjustTimeOffBalance
     */
    'note'?: string;
}

