/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantTrackingListStatusesResponseInner
 */
export interface ApplicantTrackingListStatusesResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'manageable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingListStatusesResponseInner
     */
    'translatedName'?: string;
}

