/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantTrackingGetJobSummariesResponseInnerDepartment } from './applicant-tracking-get-job-summaries-response-inner-department';
import { ApplicantTrackingGetJobSummariesResponseInnerLocation } from './applicant-tracking-get-job-summaries-response-inner-location';
import { ApplicantTrackingGetJobSummariesResponseInnerStatus } from './applicant-tracking-get-job-summaries-response-inner-status';
import { ApplicantTrackingGetJobSummariesResponseInnerTitle } from './applicant-tracking-get-job-summaries-response-inner-title';

/**
 * 
 * @export
 * @interface ApplicantTrackingGetJobSummariesResponseInner
 */
export interface ApplicantTrackingGetJobSummariesResponseInner {
    /**
     * 
     * @type {ApplicantTrackingGetJobSummariesResponseInnerTitle}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'title'?: ApplicantTrackingGetJobSummariesResponseInnerTitle;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'postedDate'?: string;
    /**
     * 
     * @type {ApplicantTrackingGetJobSummariesResponseInnerLocation}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'location'?: ApplicantTrackingGetJobSummariesResponseInnerLocation;
    /**
     * 
     * @type {ApplicantTrackingGetJobSummariesResponseInnerDepartment}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'department'?: ApplicantTrackingGetJobSummariesResponseInnerDepartment;
    /**
     * 
     * @type {ApplicantTrackingGetJobSummariesResponseInnerStatus}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'status'?: ApplicantTrackingGetJobSummariesResponseInnerStatus;
    /**
     * 
     * @type {number}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'newApplicantsCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'activeApplicantsCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'totalApplicantsCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingGetJobSummariesResponseInner
     */
    'postingUrl'?: string;
}

