/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantTrackingGetApplicationDetailsResponseJobHiringLeadJobTitle } from './applicant-tracking-get-application-details-response-job-hiring-lead-job-title';

/**
 * 
 * @export
 * @interface ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
 */
export interface ApplicantTrackingGetApplicationDetailsResponseJobHiringLead {
    /**
     * 
     * @type {number}
     * @memberof ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
     */
    'employeeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {ApplicantTrackingGetApplicationDetailsResponseJobHiringLeadJobTitle}
     * @memberof ApplicantTrackingGetApplicationDetailsResponseJobHiringLead
     */
    'jobTitle'?: ApplicantTrackingGetApplicationDetailsResponseJobHiringLeadJobTitle;
}

