/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BenefitGroup
 */
export interface BenefitGroup {
    /**
     * 
     * @type {string}
     * @memberof BenefitGroup
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitGroup
     */
    'payPeriod'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitGroup
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitGroup
     */
    'endDate'?: string;
}

