/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompanyBenefitType
 */
export interface CompanyBenefitType {
    /**
     * The name of the company benefit plan.
     * @type {string}
     * @memberof CompanyBenefitType
     */
    'name'?: string;
    /**
     * The unique identifier for the company benefit plan.
     * @type {string}
     * @memberof CompanyBenefitType
     */
    'slug'?: string;
    /**
     * Can the company benefit plan be an ACA plan.
     * @type {boolean}
     * @memberof CompanyBenefitType
     */
    'canBeAcaPlan'?: boolean;
    /**
     * Can the company benefit plan co-exist with an enrollment plan.
     * @type {boolean}
     * @memberof CompanyBenefitType
     */
    'canCoExistEnrollment'?: boolean;
    /**
     * Is the company benefit plan a reimbursement plan.
     * @type {boolean}
     * @memberof CompanyBenefitType
     */
    'isReimbursementPlan'?: boolean;
}

