/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompanyBenefitRequest
 */
export interface CompanyBenefitRequest {
    /**
     * Description
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'description'?: string;
    /**
     * Name
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'companyBenefitName'?: string;
    /**
     * Benefit vendor ID
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'benefitVendorId'?: string;
    /**
     * Benefit type
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'benefitType'?: CompanyBenefitRequestBenefitTypeEnum;
    /**
     * Deduction type ID
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'deductionTypeId'?: string;
    /**
     * Benefit start date
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'startDate'?: string;
    /**
     * Benefit end date
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'endDate'?: string;
    /**
     * Plan url
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'planUrl'?: string;
    /**
     * SSO login url
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'ssoLoginUrl'?: string;
    /**
     * SSO login link text
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'ssoLoginUrlLinkText'?: string;
    /**
     * Is a safe harbor
     * @type {boolean}
     * @memberof CompanyBenefitRequest
     */
    'safeHarbor'?: boolean;
    /**
     * Meets ACA minimum requirements
     * @type {boolean}
     * @memberof CompanyBenefitRequest
     */
    'meetAcaMin'?: boolean;
    /**
     * Reimbursement amount
     * @type {number}
     * @memberof CompanyBenefitRequest
     */
    'reimbursementAmount'?: number;
    /**
     * Reimbursement frequency
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'reimbursementFrequency'?: CompanyBenefitRequestReimbursementFrequencyEnum;
    /**
     * Reimbursement currency code
     * @type {string}
     * @memberof CompanyBenefitRequest
     */
    'reimbursementCurrencyCode'?: string;
    /**
     * Provides minimum essential coverage
     * @type {boolean}
     * @memberof CompanyBenefitRequest
     */
    'minEssentialCoverage'?: boolean;
}

type CompanyBenefitRequestBenefitTypeEnum = 'health' | 'dental' | 'vision' | 'retirement' | 'hsa' | 'flex' | 'life' | 'disability' | 'reimbursement' | 'supplemental' | 'other'
type CompanyBenefitRequestReimbursementFrequencyEnum = 'pay period' | 'month' | 'quarter' | 'year' | 'one time' | 'null'


