/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeePaystubDeductionsInner
 */
export interface EmployeePaystubDeductionsInner {
    /**
     * 
     * @type {string}
     * @memberof EmployeePaystubDeductionsInner
     */
    'externalDeductionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeePaystubDeductionsInner
     */
    'deductionDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeePaystubDeductionsInner
     */
    'deductionAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeePaystubDeductionsInner
     */
    'ytdDeductionAmount'?: string;
}

