/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesGetDirectory200Response
 */
export interface EmployeesGetDirectory200Response {
    [key: string]: any;

    /**
     * The ID of the employee
     * @type {string}
     * @memberof EmployeesGetDirectory200Response
     */
    'id'?: string;
}

