/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * What actions a user can preform on this kind of goal.
 * @export
 * @interface GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
 */
export interface GoalsGetAllAggregateInfo200ResponseFiltersInnerActions {
    /**
     * Can a goal be closed in this state.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
     */
    'canCloseGoal'?: boolean;
    /**
     * Can a goal be edited in this state.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
     */
    'canEditGoal'?: boolean;
    /**
     * Can a goal progress bar be edited in this state.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
     */
    'canEditGoalProgressBar'?: boolean;
    /**
     * Can a goal be reopened in this state.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
     */
    'canReopenGoal'?: boolean;
    /**
     * Can a goal be shared in this state.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200ResponseFiltersInnerActions
     */
    'canShareGoal'?: boolean;
}

