/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetEmployeeGoalsResponseGoalsInnerActions } from './goals-get-employee-goals-response-goals-inner-actions';
import { GoalsGetEmployeeGoalsResponseGoalsInnerMilestonesInner } from './goals-get-employee-goals-response-goals-inner-milestones-inner';

/**
 * An individual goal
 * @export
 * @interface GoalsGetEmployeeGoalsResponseGoalsInner
 */
export interface GoalsGetEmployeeGoalsResponseGoalsInner {
    /**
     * Title of the goal.
     * @type {string}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'title'?: string;
    /**
     * A description of the goal.
     * @type {string}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'description'?: string;
    /**
     * The id of the goal.
     * @type {number}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'id'?: number;
    /**
     * A percentage (1-100) that denotes how complete the goal is.
     * @type {number}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'percentComplete'?: number;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'alignsWithOptionId'?: number;
    /**
     * Ids of the employees that have access to this goal.
     * @type {Array<number>}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'sharedWithEmployeeIds'?: Array<number>;
    /**
     * The due date of the goal.
     * @type {string}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'dueDate'?: string;
    /**
     * The date the goal was completed.
     * @type {string}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'completionDate'?: string;
    /**
     * The status of the goal.
     * @type {string}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'status'?: string;
    /**
     * All milestones for the individual goal. This array will not exist if milestones are not selected for this goal.
     * @type {Array<GoalsGetEmployeeGoalsResponseGoalsInnerMilestonesInner>}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'milestones'?: Array<GoalsGetEmployeeGoalsResponseGoalsInnerMilestonesInner>;
    /**
     * 
     * @type {GoalsGetEmployeeGoalsResponseGoalsInnerActions}
     * @memberof GoalsGetEmployeeGoalsResponseGoalsInner
     */
    'actions'?: GoalsGetEmployeeGoalsResponseGoalsInnerActions;
}

