/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalsStatusCountResponseFiltersInner
 */
export interface GoalsStatusCountResponseFiltersInner {
    /**
     * Id of the filter.
     * @type {string}
     * @memberof GoalsStatusCountResponseFiltersInner
     */
    'id'?: string;
    /**
     * The name of the filter.
     * @type {string}
     * @memberof GoalsStatusCountResponseFiltersInner
     */
    'name'?: string;
    /**
     * Count of the goals with that filter.
     * @type {number}
     * @memberof GoalsStatusCountResponseFiltersInner
     */
    'count'?: number;
}

