/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalsGetAllAggregateInfoResponseGoalsInner
 */
export interface GoalsGetAllAggregateInfoResponseGoalsInner {
    /**
     * Title of the goal.
     * @type {string}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'title'?: string;
    /**
     * A description of the goal.
     * @type {string}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'description'?: string;
    /**
     * The id of the goal.
     * @type {number}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'id'?: number;
    /**
     * A percentage (1-100) that denotes how complete the goal is.
     * @type {number}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'percentComplete'?: number;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'alignsWithOptionId'?: number;
    /**
     * Ids of the employees that have access to this goal.
     * @type {Array<number>}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'sharedWithEmployeeIds'?: Array<number>;
    /**
     * The due date of the goal.
     * @type {string}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'dueDate'?: string;
    /**
     * The date the goal was completed.
     * @type {string}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'completionDate'?: string;
    /**
     * The status of the goal.
     * @type {string}
     * @memberof GoalsGetAllAggregateInfoResponseGoalsInner
     */
    'status'?: string;
}

