/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner } from './goals-get-goal-aggregate-info-response-aligns-with-options-inner';
import { GoalsGetGoalAggregateInfoResponseCommentsInner } from './goals-get-goal-aggregate-info-response-comments-inner';
import { GoalsGetGoalAggregateInfoResponseGoal } from './goals-get-goal-aggregate-info-response-goal';
import { GoalsGetGoalAggregateInfoResponsePersonsInner } from './goals-get-goal-aggregate-info-response-persons-inner';

/**
 * 
 * @export
 * @interface GoalsGetGoalAggregateInfoResponse
 */
export interface GoalsGetGoalAggregateInfoResponse {
    /**
     * 
     * @type {GoalsGetGoalAggregateInfoResponseGoal}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'goal'?: GoalsGetGoalAggregateInfoResponseGoal;
    /**
     * The selected user can align goals with other users.
     * @type {boolean}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'canAlign'?: boolean;
    /**
     * The selected user can create a goal.
     * @type {boolean}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'canCreateGoals'?: boolean;
    /**
     * All possible goals that this goal could be aligned with.
     * @type {Array<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner>}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'alignsWithOptions'?: Array<GoalsGetGoalAggregateInfoResponseAlignsWithOptionsInner>;
    /**
     * Comments linked to selected goal.
     * @type {Array<GoalsGetGoalAggregateInfoResponseCommentsInner>}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'comments'?: Array<GoalsGetGoalAggregateInfoResponseCommentsInner>;
    /**
     * A list of people with access to the goal.
     * @type {Array<GoalsGetGoalAggregateInfoResponsePersonsInner>}
     * @memberof GoalsGetGoalAggregateInfoResponse
     */
    'persons'?: Array<GoalsGetGoalAggregateInfoResponsePersonsInner>;
}

