/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Actions that are available to a goal with milestones enabled. This object will not appear on a goal without milestones.
 * @export
 * @interface GoalsGetAllAggregateInfo200Response1GoalsInnerActions
 */
export interface GoalsGetAllAggregateInfo200Response1GoalsInnerActions {
    /**
     * Can the user edit the progress bar of this goal.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200Response1GoalsInnerActions
     */
    'canEditGoalProgressBar'?: boolean;
    /**
     * can the user edit the progress of a milestone in this goal.
     * @type {boolean}
     * @memberof GoalsGetAllAggregateInfo200Response1GoalsInnerActions
     */
    'canEditGoalMilestoneProgressBar'?: boolean;
}

