/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface State
 */
export interface State {
    /**
     * The ID of the state
     * @type {number}
     * @memberof State
     */
    'id'?: number;
    /**
     * The name of the state
     * @type {string}
     * @memberof State
     */
    'name'?: string;
    /**
     * The abbreviation of the state
     * @type {string}
     * @memberof State
     */
    'abbrev'?: string;
    /**
     * The ISO standard code of the state
     * @type {string}
     * @memberof State
     */
    'iso_code'?: string;
}

