/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TableRowUpdate
 */
export interface TableRowUpdate {
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'division'?: string;
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'department'?: string;
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof TableRowUpdate
     */
    'reportsTo'?: string;
}

