/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeTrackingApproveEmployeeTimesheetsRequestTimesheetsInner } from './time-tracking-approve-employee-timesheets-request-timesheets-inner';

/**
 * 
 * @export
 * @interface TimeTrackingApproveEmployeeTimesheetsRequest
 */
export interface TimeTrackingApproveEmployeeTimesheetsRequest {
    /**
     * UNIX timestamp for last change to timesheet
     * @type {number}
     * @memberof TimeTrackingApproveEmployeeTimesheetsRequest
     */
    'lastChanged': number;
    /**
     * Array of timesheet objects that contain the timesheet id
     * @type {Array<TimeTrackingApproveEmployeeTimesheetsRequestTimesheetsInner>}
     * @memberof TimeTrackingApproveEmployeeTimesheetsRequest
     */
    'timesheets': Array<TimeTrackingApproveEmployeeTimesheetsRequestTimesheetsInner>;
}

