/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeOffRequestDatesInner } from './time-off-request-dates-inner';
import { TimeOffRequestNotesInner } from './time-off-request-notes-inner';

/**
 * 
 * @export
 * @interface TimeOffRequest
 */
export interface TimeOffRequest {
    /**
     * 
     * @type {string}
     * @memberof TimeOffRequest
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeOffRequest
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeOffRequest
     */
    'end'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeOffRequest
     */
    'timeOffTypeId'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeOffRequest
     */
    'amount'?: number;
    /**
     * 
     * @type {Array<TimeOffRequestNotesInner>}
     * @memberof TimeOffRequest
     */
    'notes'?: Array<TimeOffRequestNotesInner>;
    /**
     * 
     * @type {Array<TimeOffRequestDatesInner>}
     * @memberof TimeOffRequest
     */
    'dates'?: Array<TimeOffRequestDatesInner>;
    /**
     * 
     * @type {number}
     * @memberof TimeOffRequest
     */
    'previousRequest'?: number;
}

