/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimeTrackingStoreClockEntriesRequestEntriesInner
 */
export interface TimeTrackingStoreClockEntriesRequestEntriesInner {
    /**
     * employee id for the time entry
     * @type {number}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'employeeId'?: number;
    /**
     * date of the time entry
     * @type {string}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'date'?: string;
    /**
     * 24 hour format (hh:mm) for start time
     * @type {string}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'start'?: string;
    /**
     * 24 hour format (hh:mm) for end time
     * @type {string}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'end'?: string;
    /**
     * id of existing time entry. used when updating time entry
     * @type {number}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'clockEntryId'?: number;
    /**
     * The id of the project associated with the time entry
     * @type {number}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'projectId'?: number;
    /**
     * The id of the task associated with the time entry
     * @type {number}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'taskId'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeTrackingStoreClockEntriesRequestEntriesInner
     */
    'note'?: string;
}

