/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeTrackingClockOutEmployeeRequestClockOutLocation } from './time-tracking-clock-out-employee-request-clock-out-location';

/**
 * 
 * @export
 * @interface TimeTrackingClockOutEmployeeRequest
 */
export interface TimeTrackingClockOutEmployeeRequest {
    /**
     * 
     * @type {TimeTrackingClockOutEmployeeRequestClockOutLocation}
     * @memberof TimeTrackingClockOutEmployeeRequest
     */
    'clockOutLocation'?: TimeTrackingClockOutEmployeeRequestClockOutLocation;
}

