/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrainingAddEmployeeTrainingRecordRequestCost } from './training-add-employee-training-record-request-cost';

/**
 * 
 * @export
 * @interface TrainingAddEmployeeTrainingRecordRequest
 */
export interface TrainingAddEmployeeTrainingRecordRequest {
    /**
     * Completed is a required field and must be in yyyy-mm-dd format.
     * @type {string}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'completed': string;
    /**
     * 
     * @type {TrainingAddEmployeeTrainingRecordRequestCost}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'cost'?: TrainingAddEmployeeTrainingRecordRequestCost;
    /**
     * 
     * @type {string}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'instructor'?: string;
    /**
     * 
     * @type {number}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'credits'?: number;
    /**
     * 
     * @type {string}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'notes'?: string;
    /**
     * This must be an existing training type id.
     * @type {number}
     * @memberof TrainingAddEmployeeTrainingRecordRequest
     */
    'type': number;
}

