/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TrainingAddEmployeeTrainingRecordRequestCost } from './training-add-employee-training-record-request-cost';

/**
 * 
 * @export
 * @interface TrainingUpdateEmployeeTrainingRecordRequest
 */
export interface TrainingUpdateEmployeeTrainingRecordRequest {
    /**
     * Completed is the only required field and must be in yyyy-mm-dd format. The other parameters are optional.
     * @type {string}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'completed': string;
    /**
     * 
     * @type {TrainingAddEmployeeTrainingRecordRequestCost}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'cost'?: TrainingAddEmployeeTrainingRecordRequestCost;
    /**
     * 
     * @type {string}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'instructor'?: string;
    /**
     * 
     * @type {number}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'credits'?: number;
    /**
     * 
     * @type {number}
     * @memberof TrainingUpdateEmployeeTrainingRecordRequest
     */
    'notes'?: number;
}

