/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebHookLogResponse
 */
export interface WebHookLogResponse {
    /**
     * The id of the webhook.
     * @type {number}
     * @memberof WebHookLogResponse
     */
    'webhookId'?: number;
    /**
     * The URL of the webhook.
     * @type {string}
     * @memberof WebHookLogResponse
     */
    'url'?: string;
    /**
     * timestamp of last time the webhook was sent
     * @type {string}
     * @memberof WebHookLogResponse
     */
    'lastAttempted'?: string;
    /**
     * timestamp of last time the webhook was sent successfully
     * @type {string}
     * @memberof WebHookLogResponse
     */
    'lastSuccess'?: string;
    /**
     * Count of how many times this call failed since last success
     * @type {number}
     * @memberof WebHookLogResponse
     */
    'failureCount'?: number;
    /**
     * Status code of last request
     * @type {number}
     * @memberof WebHookLogResponse
     */
    'status'?: number;
    /**
     * A list of employee ids that were changed.
     * @type {Array<number>}
     * @memberof WebHookLogResponse
     */
    'employeeIds'?: Array<number>;
}

