/*
BambooHR API

This is the majority of the API requests including some that are not documented.

http://www.bamboohr.com/api/documentation/

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Webhook400ErrorErrorsInner } from './webhook400-error-errors-inner';

/**
 * 
 * @export
 * @interface WebhooksUpdateWebhookByIdResponse
 */
export interface WebhooksUpdateWebhookByIdResponse {
    /**
     * 
     * @type {Array<Webhook400ErrorErrorsInner>}
     * @memberof WebhooksUpdateWebhookByIdResponse
     */
    'errors'?: Array<Webhook400ErrorErrorsInner>;
}

